services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: "ZARIF SIKDER"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "ZARIF 909090"